/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1CoursesSubjectsRouteImport } from './routes/api/v1/courses/subjects'
import { Route as ApiV1CoursesSearchRouteImport } from './routes/api/v1/courses/search'
import { Route as ApiV1SharedSchedulesShareIdEventsRouteImport } from './routes/api/v1/shared-schedules/$shareId/events'
import { Route as ApiV1SectionsByCrnsTermRouteImport } from './routes/api/v1/sections/by-crns/$term'
import { Route as ApiV1SectionsPidTermRouteImport } from './routes/api/v1/sections/$pid/$term'
import { Route as ApiV1CoursesCodeSubjectCodeRouteImport } from './routes/api/v1/courses/code/$subjectCode'

const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CoursesSubjectsRoute = ApiV1CoursesSubjectsRouteImport.update({
  id: '/api/v1/courses/subjects',
  path: '/api/v1/courses/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CoursesSearchRoute = ApiV1CoursesSearchRouteImport.update({
  id: '/api/v1/courses/search',
  path: '/api/v1/courses/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SharedSchedulesShareIdEventsRoute =
  ApiV1SharedSchedulesShareIdEventsRouteImport.update({
    id: '/api/v1/shared-schedules/$shareId/events',
    path: '/api/v1/shared-schedules/$shareId/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SectionsByCrnsTermRoute = ApiV1SectionsByCrnsTermRouteImport.update({
  id: '/api/v1/sections/by-crns/$term',
  path: '/api/v1/sections/by-crns/$term',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SectionsPidTermRoute = ApiV1SectionsPidTermRouteImport.update({
  id: '/api/v1/sections/$pid/$term',
  path: '/api/v1/sections/$pid/$term',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CoursesCodeSubjectCodeRoute =
  ApiV1CoursesCodeSubjectCodeRouteImport.update({
    id: '/api/v1/courses/code/$subjectCode',
    path: '/api/v1/courses/code/$subjectCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/register': typeof RegisterRoute
  '/scheduler': typeof SchedulerRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/courses/search': typeof ApiV1CoursesSearchRoute
  '/api/v1/courses/subjects': typeof ApiV1CoursesSubjectsRoute
  '/api/v1/courses/code/$subjectCode': typeof ApiV1CoursesCodeSubjectCodeRoute
  '/api/v1/sections/$pid/$term': typeof ApiV1SectionsPidTermRoute
  '/api/v1/sections/by-crns/$term': typeof ApiV1SectionsByCrnsTermRoute
  '/api/v1/shared-schedules/$shareId/events': typeof ApiV1SharedSchedulesShareIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/register': typeof RegisterRoute
  '/scheduler': typeof SchedulerRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/courses/search': typeof ApiV1CoursesSearchRoute
  '/api/v1/courses/subjects': typeof ApiV1CoursesSubjectsRoute
  '/api/v1/courses/code/$subjectCode': typeof ApiV1CoursesCodeSubjectCodeRoute
  '/api/v1/sections/$pid/$term': typeof ApiV1SectionsPidTermRoute
  '/api/v1/sections/by-crns/$term': typeof ApiV1SectionsByCrnsTermRoute
  '/api/v1/shared-schedules/$shareId/events': typeof ApiV1SharedSchedulesShareIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/register': typeof RegisterRoute
  '/scheduler': typeof SchedulerRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/courses/search': typeof ApiV1CoursesSearchRoute
  '/api/v1/courses/subjects': typeof ApiV1CoursesSubjectsRoute
  '/api/v1/courses/code/$subjectCode': typeof ApiV1CoursesCodeSubjectCodeRoute
  '/api/v1/sections/$pid/$term': typeof ApiV1SectionsPidTermRoute
  '/api/v1/sections/by-crns/$term': typeof ApiV1SectionsByCrnsTermRoute
  '/api/v1/shared-schedules/$shareId/events': typeof ApiV1SharedSchedulesShareIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/register'
    | '/scheduler'
    | '/share/$shareId'
    | '/api/v1/health'
    | '/api/v1/courses/search'
    | '/api/v1/courses/subjects'
    | '/api/v1/courses/code/$subjectCode'
    | '/api/v1/sections/$pid/$term'
    | '/api/v1/sections/by-crns/$term'
    | '/api/v1/shared-schedules/$shareId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/register'
    | '/scheduler'
    | '/share/$shareId'
    | '/api/v1/health'
    | '/api/v1/courses/search'
    | '/api/v1/courses/subjects'
    | '/api/v1/courses/code/$subjectCode'
    | '/api/v1/sections/$pid/$term'
    | '/api/v1/sections/by-crns/$term'
    | '/api/v1/shared-schedules/$shareId/events'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/register'
    | '/scheduler'
    | '/share/$shareId'
    | '/api/v1/health'
    | '/api/v1/courses/search'
    | '/api/v1/courses/subjects'
    | '/api/v1/courses/code/$subjectCode'
    | '/api/v1/sections/$pid/$term'
    | '/api/v1/sections/by-crns/$term'
    | '/api/v1/shared-schedules/$shareId/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  RegisterRoute: typeof RegisterRoute
  SchedulerRoute: typeof SchedulerRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1CoursesSearchRoute: typeof ApiV1CoursesSearchRoute
  ApiV1CoursesSubjectsRoute: typeof ApiV1CoursesSubjectsRoute
  ApiV1CoursesCodeSubjectCodeRoute: typeof ApiV1CoursesCodeSubjectCodeRoute
  ApiV1SectionsPidTermRoute: typeof ApiV1SectionsPidTermRoute
  ApiV1SectionsByCrnsTermRoute: typeof ApiV1SectionsByCrnsTermRoute
  ApiV1SharedSchedulesShareIdEventsRoute: typeof ApiV1SharedSchedulesShareIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/courses/subjects': {
      id: '/api/v1/courses/subjects'
      path: '/api/v1/courses/subjects'
      fullPath: '/api/v1/courses/subjects'
      preLoaderRoute: typeof ApiV1CoursesSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/courses/search': {
      id: '/api/v1/courses/search'
      path: '/api/v1/courses/search'
      fullPath: '/api/v1/courses/search'
      preLoaderRoute: typeof ApiV1CoursesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/shared-schedules/$shareId/events': {
      id: '/api/v1/shared-schedules/$shareId/events'
      path: '/api/v1/shared-schedules/$shareId/events'
      fullPath: '/api/v1/shared-schedules/$shareId/events'
      preLoaderRoute: typeof ApiV1SharedSchedulesShareIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sections/by-crns/$term': {
      id: '/api/v1/sections/by-crns/$term'
      path: '/api/v1/sections/by-crns/$term'
      fullPath: '/api/v1/sections/by-crns/$term'
      preLoaderRoute: typeof ApiV1SectionsByCrnsTermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sections/$pid/$term': {
      id: '/api/v1/sections/$pid/$term'
      path: '/api/v1/sections/$pid/$term'
      fullPath: '/api/v1/sections/$pid/$term'
      preLoaderRoute: typeof ApiV1SectionsPidTermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/courses/code/$subjectCode': {
      id: '/api/v1/courses/code/$subjectCode'
      path: '/api/v1/courses/code/$subjectCode'
      fullPath: '/api/v1/courses/code/$subjectCode'
      preLoaderRoute: typeof ApiV1CoursesCodeSubjectCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  RegisterRoute: RegisterRoute,
  SchedulerRoute: SchedulerRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1CoursesSearchRoute: ApiV1CoursesSearchRoute,
  ApiV1CoursesSubjectsRoute: ApiV1CoursesSubjectsRoute,
  ApiV1CoursesCodeSubjectCodeRoute: ApiV1CoursesCodeSubjectCodeRoute,
  ApiV1SectionsPidTermRoute: ApiV1SectionsPidTermRoute,
  ApiV1SectionsByCrnsTermRoute: ApiV1SectionsByCrnsTermRoute,
  ApiV1SharedSchedulesShareIdEventsRoute:
    ApiV1SharedSchedulesShareIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
