/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as CoursesSubjectCodeRouteImport } from './routes/courses/$subjectCode'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSubjectCodeRoute = CoursesSubjectCodeRouteImport.update({
  id: '/courses/$subjectCode',
  path: '/courses/$subjectCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/register': typeof RegisterRoute
  '/scheduler': typeof SchedulerRoute
  '/courses/$subjectCode': typeof CoursesSubjectCodeRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/register': typeof RegisterRoute
  '/scheduler': typeof SchedulerRoute
  '/courses/$subjectCode': typeof CoursesSubjectCodeRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/register': typeof RegisterRoute
  '/scheduler': typeof SchedulerRoute
  '/courses/$subjectCode': typeof CoursesSubjectCodeRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/register'
    | '/scheduler'
    | '/courses/$subjectCode'
    | '/share/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/register'
    | '/scheduler'
    | '/courses/$subjectCode'
    | '/share/$shareId'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/register'
    | '/scheduler'
    | '/courses/$subjectCode'
    | '/share/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  RegisterRoute: typeof RegisterRoute
  SchedulerRoute: typeof SchedulerRoute
  CoursesSubjectCodeRoute: typeof CoursesSubjectCodeRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$subjectCode': {
      id: '/courses/$subjectCode'
      path: '/courses/$subjectCode'
      fullPath: '/courses/$subjectCode'
      preLoaderRoute: typeof CoursesSubjectCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  RegisterRoute: RegisterRoute,
  SchedulerRoute: SchedulerRoute,
  CoursesSubjectCodeRoute: CoursesSubjectCodeRoute,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
